### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
👍

**Comment by dav3r** [comment]
Doh- I approved this before I noticed that the tests are [failing the markdown linter](https://github.com/cisagov/cool-system/pull/201/checks?check_run_id=2729788783#step:7:27):
```
README.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "<div align="center">"]
```

**Comment by dav3r** [comment]
> Doh- I approved this before I noticed that the tests are [failing the markdown linter](https://github.com/cisagov/cool-system/pull/201/checks?check_run_id=2729788783#step:7:27):
> 
> ```
> README.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "<div align="center">"]
> ```

Fixed in https://github.com/cisagov/cool-system/pull/201/commits/8e0ea0f3d0cd5b704571050c956551da76c586fc.

**Review by jsf9k — APPROVED** [review]

**Review by mcdonnnj — APPROVED** [review]
🔍

**Pull request merged**
