### PR TITLE
⚠️ CONFLICT! Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by felddy**
# Lineage Pull Request: CONFLICT #

DANGER

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Clone the `lineage/skeleton` branch locally:

    ```console
    git clone --single-branch --branch lineage/skeleton git@github.com:cisagov/cool-system.git
    ```

1. Review each of the following files looking for [conflict-resolution markers](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#_basic_merge_conflicts):

    ```console
    .github/workflows/build.yml
    .mdl_config.json
    ```

1. Resolve each of the conflicts and `add` your changes to the branch:

    ```console
    git add .github/workflows/build.yml .mdl_config.json 
    ```

1. Once all the changes have been added, `commit` and `push` the changes back to
GitHub:

    ```console
    git commit --message="Resolved Lineage conflicts."
    git push
    ```

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [x] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

------------

**Note:** *You are seeing this because one of this repository's maintainers has configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by dav3r** [comment]
@felddy - Here's my feedback on the PR template:

- That flashing GIF is uber-irritating to me.  Does it really need to flash like that?
- I'd make some or all references to [Lineage](https://github.com/cisagov/action-lineage) be hyperlinks, not just the "Read more about Lineage" link at the very end.
- Each numbered step in the "How to resolve the conflicts" section should end with a consistent punctuation character (I prefer a colon).
- I would move the checkbox to directly under the `Check the "Everything is cool" checkbox below.` text.
- I'd simplify this text slightly to:
> Note: You are seeing this because one of this repository's maintainers has configured [Lineage](https://github.com/cisagov/action-lineage) to open pull requests.

Overall, I think this is great!

**Comment by hillaryj** [comment]
Seconding "make some or all references to Lineage be hyperlinks, not just the "Read more about Lineage" link at the very end." and the flashing gif is funny once and then too much. We should generally strive not to induce seizures. :)

**Comment by mcdonnnj** [comment]
I do not think the upstream project link should end in `.git`. This conflicts with the instructions to clone using SSH. I agree with others about the GIF frequency.

**Comment by felddy** [comment]
Thanks for all the great feedback.  I've incorporated the suggested changes in the description.

**Pull request merged**
